version: '3'
services:
  varnish:
    build: ./docker/varnish
    ports:
      - 8080:80
    depends_on:
      - app1
      - app2
  app1:
    image: ealen/echo-server
  app2:
    image: ealen/echo-server
