apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: /kompose convert -f - --stdout
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      ports:
        - name: "3306"
          port: 3306
          targetPort: 3306
      selector:
        io.kompose.service: db
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: /kompose convert -f - --stdout
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress
      name: wordpress
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 80
          nodePort: 30080
      selector:
        io.kompose.service: wordpress
      type: LoadBalancer
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: /kompose convert -f - --stdout
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: db
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: /kompose convert -f - --stdout
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: db
        spec:
          containers:
            - env:
                - name: MYSQL_DATABASE
                  value: exampledb
                - name: MYSQL_PASSWORD
                  value: examplepass
                - name: MYSQL_RANDOM_ROOT_PASSWORD
                  value: "1"
                - name: MYSQL_USER
                  value: exampleuser
              image: mysql:5.7
              name: db
              ports:
                - containerPort: 3306
              resources: {}
              volumeMounts:
                - mountPath: /var/lib/mysql
                  name: db
          restartPolicy: Always
          volumes:
            - name: db
              persistentVolumeClaim:
                claimName: db
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: /kompose convert -f - --stdout
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress
      name: wordpress
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: wordpress
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: /kompose convert -f - --stdout
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: wordpress
        spec:
          containers:
            - env:
                - name: WORDPRESS_DB_HOST
                  value: db
                - name: WORDPRESS_DB_NAME
                  value: exampledb
                - name: WORDPRESS_DB_PASSWORD
                  value: examplepass
                - name: WORDPRESS_DB_USER
                  value: exampleuser
              image: wordpress
              name: wordpress
              ports:
                - containerPort: 80
              resources: {}
              volumeMounts:
                - mountPath: /var/www/html
                  name: wordpress
          restartPolicy: Always
          volumes:
            - name: wordpress
              persistentVolumeClaim:
                claimName: wordpress
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress
      name: wordpress
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
kind: List
metadata: {}

