---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ealen/echo-server:0.5.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: app
  type: LoadBalancer

